"""Frozen deterministic run-status vocabulary."""

from enum import Enum


class RunStatus(str, Enum):
    CREATED = "CREATED"
    INGESTING = "INGESTING"
    INGESTED = "INGESTED"
    INTERPRETING = "INTERPRETING"
    REQUIREMENTS_ADMITTED = "REQUIREMENTS_ADMITTED"
    QC_PLANNED = "QC_PLANNED"
    INSPECTING = "INSPECTING"
    FINDINGS_READY = "FINDINGS_READY"
    REMEDIATING = "REMEDIATING"
    AWAITING_HUMAN_DECISION = "AWAITING_HUMAN_DECISION"
    DELIVERY_READY = "DELIVERY_READY"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"


TERMINAL_STATUSES = frozenset(
    {RunStatus.DELIVERY_READY, RunStatus.BLOCKED, RunStatus.FAILED}
)
